/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    DataTable: typeof import('./components/tables/DataTable.vue')['default']
    Filter: typeof import('./components/Filter.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    ModalWrapper: typeof import('./components/ModalWrapper.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
